# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IDEHospital' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IDEHospital
pod 'Alamofire', '~> 5.2'
pod 'IQKeyboardManager'
pod 'SDWebImage', '~> 5.0'
pod 'SwiftGen'
pod 'Cosmos', '~> 23.0'
end
